# docker-compose.dev.yml
version: "3"

services:
  admin-dashboard:
    container_name: admin-dashboard
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/admin-dashboard
    restart: always
    ports:
      - 3000:3000
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "testing"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  pgdata: {}
