import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer/Footer";
import { getServerSession } from "next-auth";
import Navbar from "@/components/Navbar/Navbar";
import HomePage from "@/components/HomePage/HomePage";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { authOptions } from "@/utils/authOptions";

const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomePageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-white flex bg-[#160023]",
          roboto.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        <div className="w-full">
          <HomePage>
            <ReactQueryProvider>
              <Navbar session={session} />
              {children}
              <Footer />
              <Toaster />
            </ReactQueryProvider>
          </HomePage>
        </div>
      </body>
    </html>
  );
}
